# Default values for cluster-flooder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

numberOfDeployments: 250
numberOfServices: 250

image:
  repository: kubernetes/pause
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

nodeSelector: {}